import test from 'node:test';
import assert from 'node:assert/strict';
import {createApi} from '../lib/api.mjs';
import {memoryStore} from '../lib/memory.mjs';
import {hashPassword} from '../lib/auth.mjs';
const origin='https://vote.example';
function setup(){const store=memoryStore();const api=createApi(store,{ADMIN_PASSWORD_HASH:hashPassword('a-password-long-enough','salt'),SESSION_SECRET:'a-very-long-32-character-secret-for-tests'});return {store,api};}
async function call(api,action='state',body,jar=''){const r=await api(new Request(origin+'/.netlify/functions/api?action='+action,{method:body?'POST':'GET',headers:{cookie:jar,origin,'content-type':'application/json'},...(body?{body:JSON.stringify(body)}:{})}));return {status:r.status,data:await r.json(),cookie:r.headers.getSetCookie().map(x=>x.split(';')[0]).join('; ')};}
async function voter(api){return (await call(api)).cookie;}
test('normalisation, doublon navigateur, suggestions confirmées et pourcentages',async()=>{const {api}=setup();const a=await voter(api),b=await voter(api),c=await voter(api);const s=(await call(api)).data;assert.equal((await call(api,'vote',{name:'Emmanuel Macron',epoch:s.epoch},a)).data.accepted,true);assert.equal((await call(api,'vote',{name:'Autre Personne',epoch:s.epoch},a)).status,409);await call(api,'vote',{name:' emmanuel   MACRON ',epoch:s.epoch},b);let r=await call(api,'vote',{name:'Emmanuell Macron',epoch:s.epoch},c);assert.equal(r.data.suggestions[0].name,'Emmanuel Macron');assert.equal(r.data.state.total,2);r=await call(api,'vote',{name:'Emmanuell Macron',candidateId:r.data.suggestions[0].id,epoch:s.epoch},c);assert.equal(r.data.state.total,3);assert.equal(r.data.state.candidates.length,1);assert.equal(r.data.state.candidates[0].percent,100);});
test('votes concurrents sans perte et doublons simultanés',async()=>{const {api}=setup();const jars=await Promise.all(Array.from({length:12},()=>voter(api)));const s=(await call(api)).data;const res=await Promise.all(jars.map(j=>call(api,'vote',{name:'Alice Martin',epoch:s.epoch},j)));assert.ok(res.every(r=>r.status===200));assert.equal((await call(api)).data.total,12);const j=await voter(api);const dup=await Promise.all([1,2].map(()=>call(api,'vote',{name:'Alice Martin',epoch:s.epoch},j)));assert.deepEqual(dup.map(r=>r.status).sort(),[200,409]);});
test('administration protégée, fermeture, suppression, reset et anciens formulaires',async()=>{const {api}=setup();let s=(await call(api)).data;assert.equal((await call(api,'reset',{epoch:s.epoch,revision:s.revision})).status,401);const j=await voter(api);await call(api,'vote',{name:'Alice Martin',epoch:s.epoch},j);const login=await call(api,'login',{password:'a-password-long-enough'});const admin=login.cookie;s=(await call(api)).data;let r=await call(api,'delete',{id:s.candidates[0].id,epoch:s.epoch,revision:s.revision},admin);assert.equal(r.status,200);assert.equal(r.data.total,0);assert.equal((await call(api,'vote',{name:'Alice Martin',epoch:s.epoch},j)).status,409);s=(await call(api)).data;r=await call(api,'settings',{title:'Un sujet',description:'Texte provisoire',cta:'Voter',closed:true,epoch:s.epoch,revision:s.revision},admin);assert.equal(r.status,200);assert.equal((await call(api,'vote',{name:'Alice Martin',epoch:s.epoch},await voter(api))).status,409);s=(await call(api)).data;r=await call(api,'reset',{epoch:s.epoch,revision:s.revision},admin);assert.notEqual(r.data.epoch,s.epoch);assert.equal(r.data.closed,true);assert.equal((await call(api,'vote',{name:'Alice Martin',epoch:s.epoch},j)).status,409);});
test('validation, origine, sessions et limitation des tentatives',async()=>{const {api}=setup();const j=await voter(api),s=(await call(api)).data;assert.equal((await call(api,'vote',{name:'<script>alert(1)</script>',epoch:s.epoch},j)).status,400);assert.equal((await call(api,'vote',{name:'Martin',epoch:s.epoch},j)).status,400);const r=await api(new Request(origin+'/.netlify/functions/api?action=login',{method:'POST',headers:{origin:'https://evil.example','content-type':'application/json'},body:'{}'}));assert.equal(r.status,403);for(let i=0;i<10;i++)assert.equal((await call(api,'login',{password:'bad'})).status,401);assert.equal((await call(api,'login',{password:'bad'})).status,429);});
test('reset autorise un nouveau vote, variantes accentuées et réponse nouvelle confirmée',async()=>{const {api}=setup();const j=await voter(api),j2=await voter(api),j3=await voter(api);let s=(await call(api)).data;await call(api,'vote',{name:'Élise Martin',epoch:s.epoch},j);await call(api,'vote',{name:'elise MARTIN',epoch:s.epoch},j2);const r=await call(api,'vote',{name:'Elisa Martin',epoch:s.epoch,confirmNew:true},j3);assert.equal(r.data.state.total,3);assert.equal(r.data.state.candidates.length,2);const admin=(await call(api,'login',{password:'a-password-long-enough'})).cookie;s=(await call(api)).data;const reset=await call(api,'reset',{epoch:s.epoch,revision:s.revision},admin);assert.equal((await call(api,'vote',{name:'Élise Martin',epoch:reset.data.epoch},j)).data.accepted,true);});
