import {randomUUID,createHash} from 'node:crypto';
import {initial,mutate,publicState,cast,HttpError} from './model.mjs';
import {cookies,cookie,verified,session,checkPassword} from './auth.mjs';
export function createApi(store,env=process.env){return async req=>{const headers=new Headers({'content-type':'application/json; charset=utf-8','cache-control':'no-store'});const send=(data,status=200)=>new Response(JSON.stringify(data),{status,headers});try{const url=new URL(req.url),action=url.searchParams.get('action')||'state',ck=cookies(req);let id=ck.voix_browser;if(!/^[a-f0-9-]{36}$/.test(id||'')){id=randomUUID();headers.append('set-cookie',cookie(req,'voix_browser',id,31536000));}
if(!['GET','POST'].includes(req.method))throw new HttpError(405,'Méthode non autorisée.');
if(req.method==='GET'){if(action!=='state')throw new HttpError(404,'Action inconnue.');const entry=await store.getWithMetadata('poll',{type:'json',consistency:'strong'});const s=entry?.data||(await mutate(store,'poll',()=>{})).state;return send({...publicState(s,id),admin:!!env.SESSION_SECRET&&verified(ck.voix_admin||'',env.SESSION_SECRET)});}
if(req.headers.get('origin')!==url.origin)throw new HttpError(403,'Origine de la requête refusée.');if(!req.headers.get('content-type')?.startsWith('application/json'))throw new HttpError(415,'Format JSON attendu.');const raw=await req.text();if(raw.length>8192)throw new HttpError(413,'Formulaire trop volumineux.');let input;try{input=JSON.parse(raw);}catch{throw new HttpError(400,'Formulaire invalide.');}if(!input||typeof input!=='object'||Array.isArray(input))throw new HttpError(400,'Formulaire invalide.');
if(action==='vote'){if(!ck.voix_browser)throw new HttpError(400,'Activez les cookies puis actualisez la page.');const {state,result}=await mutate(store,'poll',s=>cast(s,id,input));return send({...result,state:publicState(state,id)});}
if(!env.ADMIN_PASSWORD_HASH||!env.SESSION_SECRET||env.SESSION_SECRET.length<32)throw new HttpError(503,'Administration non configurée : définissez ADMIN_PASSWORD_HASH et SESSION_SECRET dans Netlify.');
if(action==='login'){const ip=req.headers.get('x-nf-client-connection-ip')||'local';const key='login/'+createHash('sha256').update(ip).digest('hex');await mutate(store,key,s=>{if(Date.now()-s.start>15*60000){s.start=Date.now();s.count=0;}if(s.count>=10)throw new HttpError(429,'Trop de tentatives. Réessayez dans 15 minutes.');s.count++;},()=>({start:Date.now(),count:0}));if(typeof input.password!=='string'||input.password.length>200||!checkPassword(input.password,env.ADMIN_PASSWORD_HASH))throw new HttpError(401,'Mot de passe incorrect.');headers.append('set-cookie',cookie(req,'voix_admin',session(env.SESSION_SECRET),8*3600));return send({ok:true});}
if(action==='logout'){headers.append('set-cookie',cookie(req,'voix_admin','',0));return send({ok:true});}
if(!verified(ck.voix_admin||'',env.SESSION_SECRET))throw new HttpError(401,'Connectez-vous à l’administration.');
if(!['settings','delete','reset'].includes(action))throw new HttpError(404,'Action inconnue.');
const {state}=await mutate(store,'poll',s=>{if(input.epoch!==s.epoch)throw new HttpError(409,'Consultation réinitialisée : actualisez la page.');if(input.revision!==s.revision)throw new HttpError(409,'Les données ont changé : actualisez avant de recommencer.');if(action==='settings'){for(const [k,max] of [['title',180],['description',1200],['cta',50]]){if(typeof input[k]!=='string'||!input[k].trim()||input[k].length>max)throw new HttpError(400,'Les textes sont obligatoires et doivent respecter les longueurs indiquées.');s[k]=input[k].trim();}if(typeof input.closed!=='boolean')throw new HttpError(400,'Statut invalide.');s.closed=input.closed;}if(action==='delete'){if(!s.candidates.some(c=>c.id===input.id))throw new HttpError(404,'Réponse introuvable.');s.candidates=s.candidates.filter(c=>c.id!==input.id);}if(action==='reset'){s.epoch=randomUUID();s.candidates=[];s.voters={};}});return send(publicState(state,id));
}catch(e){if(!(e instanceof HttpError))console.error('vote-api:',e.message);return send({error:e instanceof HttpError?e.message:'Service momentanément indisponible. Réessayez.'},e.status||500);}};}
