import {createHash,randomUUID} from 'node:crypto';
export class HttpError extends Error { constructor(status,message){super(message);this.status=status;} }
export const initial = () => ({epoch:randomUUID(),revision:0,title:'Qui mérite votre voix ?',description:'Une personne vous inspire ? Faites entendre votre voix et découvrez les résultats de cette consultation.',cta:'Je vote',closed:false,candidates:[],voters:{}});
export const normalize = s => s.normalize('NFKD').replace(/\p{M}/gu,'').toLowerCase().replace(/[’']/g,' ').replace(/[-‐‑]/g,' ').replace(/\s+/g,' ').trim();
export function validName(s){if(typeof s!=='string')throw new HttpError(400,'Saisissez un nom et un prénom.');s=s.trim().replace(/\s+/g,' ');if(s.length<3||s.length>100||! /^[\p{L}\p{M} .’'‐‑-]+$/u.test(s)||s.split(' ').length<2)throw new HttpError(400,'Saisissez un nom et un prénom (3 à 100 caractères, sans chiffres).');return s;}
export function distance(a,b){let row=Array.from({length:b.length+1},(_,i)=>i);for(let i=1;i<=a.length;i++){let next=[i];for(let j=1;j<=b.length;j++)next[j]=Math.min(next[j-1]+1,row[j]+1,row[j-1]+(a[i-1]!==b[j-1]));row=next;}return row[b.length];}
export function suggestions(state,name){const n=normalize(validName(name));return state.candidates.map(c=>({...c,distance:distance(n,c.key)})).filter(c=>c.distance>0&&c.distance<=Math.min(3,Math.max(1,Math.floor(n.length*.2)))).sort((a,b)=>a.distance-b.distance).slice(0,3).map(({id,name})=>({id,name}));}
export const voterKey=id=>createHash('sha256').update(id).digest('hex');
export function publicState(s,id){let total=s.candidates.reduce((n,c)=>n+c.votes,0);return {epoch:s.epoch,revision:s.revision,title:s.title,description:s.description,cta:s.cta,closed:s.closed,total,voted:!!s.voters[voterKey(id)],candidates:[...s.candidates].sort((a,b)=>b.votes-a.votes||a.name.localeCompare(b.name,'fr')).map(({id,name,votes})=>({id,name,votes,percent:total?Math.round(votes/total*1000)/10:0}))};}
export function cast(s,id,input){if(input.epoch!==s.epoch)throw new HttpError(409,'La consultation a été réinitialisée. Actualisez la page.');if(s.closed)throw new HttpError(409,'Le vote est clôturé.');const v=voterKey(id);if(s.voters[v])throw new HttpError(409,'Vous avez déjà voté depuis ce navigateur.');const name=validName(input.name);let c=input.candidateId?s.candidates.find(c=>c.id===input.candidateId):s.candidates.find(c=>c.key===normalize(name));if(input.candidateId&&!c)throw new HttpError(409,'Cette réponse a été supprimée. Recommencez votre saisie.');if(!c&&!input.confirmNew){const near=suggestions(s,name);if(near.length)return {suggestions:near};}if(!c){c={id:randomUUID(),name,key:normalize(name),votes:0};s.candidates.push(c);}c.votes++;s.voters[v]=true;return {accepted:true,name:c.name};}
export async function mutate(store,key,fn,seed=initial){for(let i=0;i<20;i++){const entry=await store.getWithMetadata(key,{type:'json',consistency:'strong'});const s=entry?entry.data:seed();const result=fn(s);s.revision=(s.revision||0)+1;const {modified}=await store.setJSON(key,s,entry?{onlyIfMatch:entry.etag}:{onlyIfNew:true});if(modified)return {state:s,result};await new Promise(r=>setTimeout(r,10+Math.random()*40));}throw new HttpError(503,'Trop de votes simultanés. Réessayez dans quelques secondes.');}
